### ISSUE TITLE
Commands to enable/disable line_num aren't being created even though module is enabled in config

### ISSUE THREAD

**Issue by sjclayton** [shellRaining/hlchunk.nvim#103]
**Describe the bug**

line_num module enable / disable cmd's not being created even though module is enabled in configuration.

**To Reproduce**

1. Enable line_num module in hlchunk.nvim configuration (line number highlights show up as intended).
2. Try to disable hlchunk line number highlight with `:DisableHLline_num` or `:DisableHLLineNum`.
3. Neither command is present, confirmed by autocomplete. The commands for the other two modules I have enabled show up and work (chunk and ident).

**Expected behavior**

Line number highlights are enabled / disabled using the defined commands.

**Additional information**

I'm running Neovim 0.10

**Comment by shellRaining** [comment]
yes, `EnableHLline_num` is an invalid usercmd name, I will fix this

**Comment by shellRaining** [comment]
fixed in dev branch，temporarily close this issue. 
And dev has many new feature (like animation for chunk), I will merge when it is stable
