### ISSUE TITLE
Chunk lines are not cleared after scroll window

### ISSUE THREAD

**Issue by ShiChenCong** [shellRaining/hlchunk.nvim#104]
![Untitled](https://github.com/shellRaining/hlchunk.nvim/assets/22486446/3f3aeb2a-5242-4e56-99b2-9cfb4c12d9f9)

config file
```
  {
    "shellRaining/hlchunk.nvim",
    event = { "BufReadPre", "BufNewFile" },
    config = function()
      require("hlchunk").setup({
        chunk = {
          enable = true,
          style = {
            { fg = "#8c98a3" },
          },
        }
      })
    end
  },
```
nvim version: 0.10.0

**Comment by shellRaining** [comment]
fixed in dev branch，temporarily close this issue.
And dev has many new feature (like animation for chunk), I will merge when it is stable

**Comment by ShiChenCong** [comment]
broken in `less` file in dev branch.

**Comment by shellRaining** [comment]
It seems to be caused by the lack of a treesitter parser for `less`.

**Comment by ShiChenCong** [comment]
How to disable plugin for some certain filetypes?

**Comment by shellRaining** [comment]
If you simply do not want to see the information of notify, you can set `notify = false`

https://github.com/shellRaining/hlchunk.nvim/blob/main/docs/en/chunk.md#chunk_example1

if does want to disable, just set:

```lua
chunk = {
    enable = true,
    exclude_filetypes = {
        less = true,
    },
},
```
