### ISSUE TITLE
New changes re-introduce text-hiding bugs

### ISSUE THREAD

**Issue by serhez** [shellRaining/hlchunk.nvim#106]
**Describe the bug**
The new big changes that have come in the last several days have re-introduced bugs I had experienced in the past relating to the indent guides having higher priority than the real text in the buffer, therefore hiding the text. Personally, I have been unable to use the plugin because I often can't read the text in my files.

**To Reproduce**
I am now encountering these bugs quite regularly, so I don't think there is the need to give a specific example. You should encounter the bug by just opening a large text file with different indentation levels and trying to press `<<` (in normal mode) several times on a deeply indented line. If you do need a specific example, let me know.

**Expected behavior**
I expect indent guides to never hide real text in any situation. It's quite possible I'm missing something, but couldn't the priority of the indent guides text simply be always lower than the real text? Perhaps it would be useful to see how `indent-blankline` does it, since this issue does not exist in that plugin?

**Screenshots**

A stupid badly-formatted example to showcase the issue (but I often encounter this issue in my real well-formatted code):
![Screenshot 2024-06-10 at 00 12 28](https://github.com/shellRaining/hlchunk.nvim/assets/18057093/911771e6-762a-417f-968d-2c983b210d83)

**Extra information**

Thanks for the amazing plugin :)

**Comment by serhez** [comment]
I've been trying different previous commits to see where these problems were re-introduced. In commit `919621eeb7225ee16b41fe19e140fa07f505e308`, this issue does not seem to happen (but I haven't thoroughly tested).

**Comment by shellRaining** [comment]
You may have enabled the `use_treesitter` option. I found it caused because following code was deleted (for bad perf)

https://github.com/shellRaining/hlchunk.nvim/blob/2f25e09d2d0a2c121225a46e8cfe3ff11225ac79/lua/hlchunk/mods/indent/init.lua#L48-L54

By the way, It is not recommended to use treesitter now, as for the more precise features mentioned earlier, I will try to make up for it.

**Comment by shellRaining** [comment]
latest version fix this~
