### ISSUE TITLE
Chunk guides hidden behind indent guides

### ISSUE THREAD

**Issue by serhez** [shellRaining/hlchunk.nvim#107]
**Describe the bug**
The chunk guides are most of the time partially hidden behind the indent guides (see video attached).

**To Reproduce**
Scroll up and down in code with nested indentation. My config is below; you may need to replace the references to my color and icons helpers. I've also tried setting `chunk.use_treesitter = false` but it doesn't help.

```lua
require("hlchunk").setup({
    chunk = {
        enable = true,
        use_treesitter = true,
        notify = true,
        chars = {
            horizontal_line = icons.bar.horizontal_thin,
            vertical_line = icons.bar.vertical_center_thin,
            left_top = icons.bar.upper_left_corner_thin,
            left_bottom = icons.bar.lower_left_corner_thin,
            right_arrow = icons.bar.horizontal_thin,
        },
        textobject = "ic",
        style = {
            {
                fg = c.info_fg, -- no error
            },
            {
                fg = c.error_fg, -- error
            },
        },
        -- FIX: The animation creates artifacts when moving the cursor fast
        -- duration = 150,
        -- delay = 1,
        duration = 0,
        delay = 0,
    },
    
    indent = {
        enable = true,
        use_treesitter = false,
        chars = {
            icons.bar.vertical_center_thin,
        },
        style = {
            {
                fg = c.comment_fg,
            },
        },
        delay = 0,
    },
    
    line_num = {
        enable = false,
    },
    
    blank = {
        enable = false,
    },
})
```

**Expected behavior**
The chunk guides should have preference over indent guides.

**Screenshots**

https://github.com/shellRaining/hlchunk.nvim/assets/18057093/65b1c3a3-abfc-41e1-aee2-dac895c46b79

**Comment by shellRaining** [comment]
Sorry, the previous issue was not explained clearly. The `indent` mod does not need to set the `use_treesitter` option to `true`, but `chunk` still relies more on treesitter (because they work differently).

as for the bug, I can't reproduce it.


https://github.com/shellRaining/hlchunk.nvim/assets/111564053/cf3b0c9e-47f5-495c-9056-75ddc3c77f26

**Comment by serhez** [comment]
@shellRaining Thanks for the explanation! I tried setting a higher priority for the chunk mod, but this doesn't solve the issue. Could you try reproducing with my config or sharing yours? It's strange that we wouldn't get the same behavior.

**Comment by shellRaining** [comment]
I'll take a look at your dotfile, by the way, your color scheme looks great!

**Comment by serhez** [comment]
@shellRaining Ok perfect! ❤️
