### ISSUE TITLE
chunk not redrawn when toggling a comment line

### ISSUE THREAD

**Issue by soifou** [shellRaining/hlchunk.nvim#109]
**Describe the bug**
The redraw is discarded when toggling one or several lines inside a chunk using the builtin comment (eg `gcc`) yielding to a non-continuous vertical line. Undoing restore it though. See video below.

**To Reproduce**

```sh
nvim -nu repro.lua repro.lua
```

```lua
local root = vim.fn.fnamemodify('./.repro', ':p')

for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
    vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
end

local lazypath = root .. '/plugins/lazy.nvim'
if not vim.uv.fs_stat(lazypath) then
    vim.fn.system({
        'git',
        'clone',
        '--filter=blob:none',
        '--single-branch',
        'https://github.com/folke/lazy.nvim.git',
        lazypath,
    })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
    {
        'shellRaining/hlchunk.nvim',
        opts = {
            chunk = {
                enable = true,
            },
        },
    }
}
require('lazy').setup(plugins, {
    root = root .. '/plugins',
})

vim.opt.termguicolors = true
```

**Screenshots**

https://github.com/shellRaining/hlchunk.nvim/assets/7377369/faed698d-cfd4-43b4-bbea-cebba4f72609

**Comment by shellRaining** [comment]
chunk will have diff operation between pre chunk and the new chunk when rendering, when you press `gcc` the text changed and autocmd does trigger, but the render char not changed, so actually not render actually, I will figure out how the comment plugin work.

**Comment by shellRaining** [comment]
it seems that `comment.nvim` use `nvim_buf_set_lines()` instead of `nvim_buf_set_text()` caused this, the first function will remove extmark when change text, I will take a issue in this repo

**Comment by soifou** [comment]
FWIW, I don't use any comment plugin but the now [builtin comment implementation](https://github.com/neovim/neovim/commit/73de98256cf3932dca156fbfd0c82c1cc10d487e) that comes with nvim 0.10. It use as well `nvim_buf_set_lines()` as shown [here](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/_comment.lua#L181)

**Comment by shellRaining** [comment]
I also found that https://github.com/numToStr/Comment.nvim/issues/52 and https://github.com/numToStr/Comment.nvim/pull/110 mentioned this, seems can solve this, but the example I can't fully understand

**Comment by shellRaining** [comment]
fix by add lazy field when rendering, if comment a line then re-render with no lazy option passed

**Comment by soifou** [comment]
This works great! Thank you so much for the quick fix.
