### ISSUE TITLE
indent: shifting leftwards leads to visual glitch

### ISSUE THREAD

**Issue by soifou** [shellRaining/hlchunk.nvim#110]
**Describe the bug**
Using indent module, when you shift leftwards (`<<`) you'll see the character redrawn above the indent guide. Shifting righwards (`>>`) does not.

**Screenshots**

https://github.com/shellRaining/hlchunk.nvim/assets/7377369/e26d7a9c-9547-44fc-b5d7-f05361a74ce9

**Comment by shellRaining** [comment]
Actually it not a bug, indent set a `delay` field to enhance performance, default is `100` ms, you can set it to `0` to avoid flickering during rendering.
