### ISSUE TITLE
Chunk highlight the whole first indent of a buffer

### ISSUE THREAD

**Issue by soifou** [shellRaining/hlchunk.nvim#113]
**Describe the bug**
This is a bug and by extend a proposal feature. 

With chunk enabled when you jump into a buffer with some content, whatever allowed filetype, that lead to the first line, the first indent is then highlighted in the whole buffer. This happen only in this case. If you move your cursor everything gets correctly "init".

**To Reproduce**
1. `nvim README.md +1`
2. First indent highlighted in the whole buffer

**Expected behavior**
Chunk should be correctly initialized

**Screenshots**
![image](https://github.com/shellRaining/hlchunk.nvim/assets/7377369/db17e10c-9b36-4bb4-8db5-1e0ba5d25df6)
![image](https://github.com/shellRaining/hlchunk.nvim/assets/7377369/077cddfd-2ca1-4230-a754-846c9d1c0e1c)

**Additional context**
Additionally, it could be nice to have an option to disable the first level of indent, like indent-blankline.nvim already does. This seems to be frequently asked in this kind of plugin like [here](https://github.com/lukas-reineke/indent-blankline.nvim/issues/824) or [there](https://github.com/nvimdev/indentmini.nvim/issues/23)

Personally I often feel this pointless when browsing code and add unnecessary visual clutter.

What do you think? Is this something fairly easy to implement?

**Comment by shellRaining** [comment]
sorry but I can't reproduce this bug, can you provide more details.

and the feat you mentioned has been achieved. The effect is as follows

![without_first_level](https://github.com/shellRaining/hlchunk.nvim/assets/111564053/3877d2d6-243f-4b3b-8339-1c970c83bbe5)

after refactor I will publish and upload

**Comment by soifou** [comment]
Very nice! Would you mind to disable the chunk effect as well on the first indent? If the user want to disable the first indent on indent module, he might want to do the same for the chunk module.

Here is the repro, this clearly has something to do using lazy-load on specific event like `BufEnter`, `UIEnter` or `ColorScheme`. I should have mentioned it, sorry!

```sh
nvim -nu repro.lua README.md +1
```

```lua
  local root = vim.fn.fnamemodify('./.repro', ':p')

  for _, name in ipairs({ 'config', 'data', 'state', 'cache' }) do
      vim.env[('XDG_%s_HOME'):format(name:upper())] = root .. '/' .. name
  end

  local lazypath = root .. '/plugins/lazy.nvim'
  if not vim.uv.fs_stat(lazypath) then
      vim.fn.system({
          'git',
          'clone',
          '--filter=blob:none',
          '--single-branch',
          'https://github.com/folke/lazy.nvim.git',
          lazypath,
      })
  end
  vim.opt.runtimepath:prepend(lazypath)

  local plugins = {
      {
          'shellRaining/hlchunk.nvim',
          event = 'BufEnter', -- or UIEnter, ColorScheme
          lazy = true,
          opts = {
              chunk = {
                  enable = true,
              },
          },
      },
  }
  require('lazy').setup(plugins, {
      root = root .. '/plugins',
  })

  vim.opt.termguicolors = true
```

**Comment by shellRaining** [comment]
very thanks for your detailed report, I have fixed this in latest commit

**Comment by shellRaining** [comment]
> Very nice! Would you mind to disable the chunk effect as well on the first indent? If the user want to disable the first indent on indent module, he might want to do the same for the chunk module.

yes, however chunk and textobjecgt are related, if a chunk is not rendered, it may be confused
