### ISSUE TITLE
i guess we do this already using `chunk`/`indent` but nonetheless...

### ISSUE THREAD

**Issue by daUnknownCoder** [shellRaining/hlchunk.nvim#118]
if we can get this in `chunk` (one node) / `indent` (whole file) it will be great:
![image](https://github.com/shellRaining/hlchunk.nvim/assets/84800625/539b3b68-0b43-4ba5-b8e3-52ff33e615f1)

so adding fold support will do good:
Inspiration: https://github.com/gh-liu/fold_line.nvim

**Comment by shellRaining** [comment]
Feels interesting, but will doing this cause serious performance issues? I'll try out the plugin you mentioned first.

**Comment by daUnknownCoder** [comment]
> Feels interesting, but will doing this cause serious performance issues? I'll try out the plugin you mentioned first.

check this: gh-liu/fold_line.nvim#1

**Comment by shellRaining** [comment]
can this display effect meet your need

![IMG_20240623_203145_949.jpg](https://github.com/shellRaining/hlchunk.nvim/assets/111564053/3fb4a2f3-2a48-4cbe-b783-347fce550714)

**Comment by daUnknownCoder** [comment]
> can this display effect meet your need

wait, thats real cool :lmao: tho the `start of line` as in `return` got messed up but we can use the `rounded_border` glyph for that anyway

can we do this for the current context only tho? coz it may coz perf drops if we do this with the whole file so i guess this is going towards `chunk` :damn:

tho this almost looks like the plugin

**Comment by shellRaining** [comment]
this is impl by using `ibl.hook` and `statucol.nvim`, I have write a demo like below

the first one 

<img width="840" alt="image" src="https://github.com/shellRaining/hlchunk.nvim/assets/111564053/b052aea1-174e-4a61-8a57-f4a60eec347e">

the second one

![image](https://github.com/shellRaining/hlchunk.nvim/assets/111564053/bedced9e-0b9e-45f0-9bda-37ed2594a1c3)

which one you like better

**Comment by daUnknownCoder** [comment]
1. the first one (what happened to ur symbols in the second one tho 💀?)
2. whats the difference?

what ~godly~ font are you using? 

![Add a little bit of body text](https://github.com/shellRaining/hlchunk.nvim/assets/84800625/6cfde52e-5a26-47be-a0c1-331f77396a4c)
![Add a little bit of body text (1)](https://github.com/shellRaining/hlchunk.nvim/assets/84800625/3ceb299c-20bd-460c-b2eb-bf908fd03cd4)

i have just edited the image but is this possible (more similarity to the plugin) tho only when the respective fold is closed

**Comment by shellRaining** [comment]
> 1. the first one (what happened to ur symbols in the second one tho 💀?)

the second one use different char and highlight

> 2. whats the difference?

the first render in the max level indent line, while the second only render in the first level

> what ~godly~ font are you using?

```toml
[font]
size = 12

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.italic]
family = "VictorMono NFM"
style = "Italic"
```

> i have just edited the image but is this possible (more similarity to the plugin) tho only when the respective fold is closed

no, `hlchunk` only set `extmark`, not monitor fold info... maybe you can search for other plugin

**Comment by daUnknownCoder** [comment]
> no, `hlchunk` only set `extmark`, not monitor fold info... maybe you can search for other plugin

can we just add another spec for `indent` like `chunk` having `chars`, something like:
```lua
chars = {
        vertical_line = "│", -- or `vertical_line` to be passed as a table for multiple indent chars
        left_top = "╭",
        left_bottom = "╰",
    },
```

**Comment by shellRaining** [comment]
no, under the current conditions, it is impossible to achieve the style effect of `fold-line`. It is necessary to inherit the `indent` mod and rewrite the `render` function.

**Comment by daUnknownCoder** [comment]
> no, under the current conditions, it is impossible to achieve the style effect of `fold-line`. It is necessary to inherit the `indent` mod and rewrite the `render` function.

no im just asking if we can add `indent start` and `indent end` characters

**Comment by shellRaining** [comment]
in the dev brach, you can use `filter_list` to define your own hook to achieve this, but this field still unstable, maybe change in future...

**Comment by shellRaining** [comment]
After considering for a while, I feel that the above implementation has a significant impact on performance and is not conducive to code maintenance. temporarily close this issue, and if I have any ideas for refactoring in the future, I may reopen it.
