### ISSUE TITLE
indent is not enabled.

### ISSUE THREAD

**Issue by iokira** [shellRaining/hlchunk.nvim#119]
Thanks for all the great plugins. I am reporting that since commit  [44ee797](https://github.com/shellRaining/hlchunk.nvim/commit/44ee79795fdde6a0f3af588c160059d548911d31), the indent feature is not enabled.

I started nvim with the following command and loaded the plugin using lazy.nvim, but the indent feature was not enabled.
![Screenshot 2024-06-23 at 20 45 32](https://github.com/shellRaining/hlchunk.nvim/assets/54161041/ad91dd6c-85b2-48f0-a4b1-4928d417aea3)

```sh
nvim -u init.lua init.lua
```

init.lua

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    vim.fn.system({
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/folke/lazy.nvim.git",
        "--branch=stable",
        lazypath,
    })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
    {
        "shellRaining/hlchunk.nvim",
        lazy = true,
        event = { "BufReadPre", "BufAdd", "BufNewFile" },
        config = function()
            require("hlchunk").setup({
                indent = {
                    enable = true,
                },
            })
        end,
    },
})
```

Before commit [f4e8e1a](https://github.com/shellRaining/hlchunk.nvim/commit/f4e8e1a12e16abbd05aca216837904a02c9049a0), the indent feature was enabled successfully.
![Screenshot 2024-06-23 at 20 45 07](https://github.com/shellRaining/hlchunk.nvim/assets/54161041/c437564e-56da-4484-9662-afbf2d4d4a32)

This is my first bug report, so sorry if there are any poor or missing parts.

**Comment by shellRaining** [comment]
thanks for your detail report first!

but for sorry I can't reproduce this bug, I touch a file `repro.lua` first, and paste the code you provide, and run `nvim -u repro.lua init.lua`, it render properly

<img width="615" alt="image" src="https://github.com/shellRaining/hlchunk.nvim/assets/111564053/0d02a6ba-6dd3-44d1-99d0-0825180cac43">

and what version or branch are you using now, I'm testing in dev branch

**Comment by iokira** [comment]
Thanks for the quick response.
The version of nvim I am using was 0.9.5.
I updated to 0.10.0 ASAP and the indent function works fine.
I will try again using the plugin with nvim version 0.9.5 and see if I can reproduce the bug!

**Comment by shellRaining** [comment]
glad that issue resolved, but what confuses me is that I did not use the API of `Neovim 0.10.0`, maybe there exist some other bug...

**Comment by iokira** [comment]
At any rate, I am glad the problem is solved. I will close the issue as I don't see anyone else experiencing the same bug. If I find the cause of the problem, I will contact you again. Thanks for your valuable time!
