### ISSUE TITLE
Strange error on ubuntu installation

### ISSUE THREAD

**Issue by Mitra98t** [shellRaining/hlchunk.nvim#124]
Nvim notifies me with an error about hlchunk un my ubuntu installation.
I originally created the configs on macos, after pulling on ubuntu hlchink gave me errors.

I get the error every time e change "chunk", meaning getting the cursor from a function to another for example

This is the error:
![error_image](https://github.com/user-attachments/assets/f62a2ded-d1e7-40d2-988f-48cde3617c0a)

I'm running nvim v0.10.0-dev on ubuntu 20.04

**Comment by shellRaining** [comment]
maybe `nvim v0.10.0-dev` change the name of `get_indent`... I'll have a test

**Comment by shellRaining** [comment]
similar with #129, update to nvim v0.10.0 will fix this
