### ISSUE TITLE
Add a config type e.g. `---@type hlchunk.config`

### ISSUE THREAD

**Issue by nihaals** [shellRaining/hlchunk.nvim#128]
**Is your feature request related to a problem? Please describe.**
It's helpful having autocomplete for config fields. It looks like the project already uses types but because of how it dynamically passes config to each module, there isn't an existing type that someone could use for something like:
```lua
---@type hlchunk.config
opts = {},
```

**Describe the solution you'd like**
A single type that could be used similarly to above.

**Describe alternatives you've considered**
You can write your own or just not use one, which works but isn't as nice of an experience as having a type.

**Comment by shellRaining** [comment]
I apologize for being busy with my internship and other interests lately, so I may not be able to handle this part promptly.
and pr welcome
