### ISSUE TITLE
Error detected while processing WinScrolled Autocommands for "*"

### ISSUE THREAD

**Issue by CBaier33** [shellRaining/hlchunk.nvim#129]
**Describe the bug**
- After installing the plugin, I get immediate autocmd errors. The plugin features will render, but any action will trigger some sort of error.

**To Reproduce**
- Install the plugin with lazy.nvim

**Screenshots**

![Screenshot from 2024-08-18 23-27-56](https://github.com/user-attachments/assets/322b1a50-cca4-48a6-8a5a-da0bc1bf3a03)

![Screenshot from 2024-08-18 23-31-54](https://github.com/user-attachments/assets/1b9f957c-b439-4e74-908c-eaa676f7415c)

![Screenshot from 2024-08-18 23-30-27](https://github.com/user-attachments/assets/8e0dd284-09f5-4029-a221-2da9a3bd0695)

**Additional context**

treesitter configuration:
![Screenshot from 2024-08-18 23-34-53](https://github.com/user-attachments/assets/641eb60f-6b03-4cff-b2f7-eb3f741d0797)

**Comment by shellRaining** [comment]
May I know which version of Neovim you are using? If it's the nightly version, it might throw an error

**Comment by CBaier33** [comment]
```
❯ nvim -v
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by micsama** [comment]
me too. the same problem 
Error detected while processing CursorMoved Autocommands for "*":
E464: Ambiguous use of user-defined command: EnableHL

**Comment by shellRaining** [comment]
@CBaier33  @micsama  This issue is related to the neovim version, it is recommended to use nvim 0.10 or later.
