### ISSUE TITLE
Missed cache invalidation for indent guidelines

### ISSUE THREAD

**Issue by jbarap** [shellRaining/hlchunk.nvim#130]
**Describe the bug**
Great plugin! Love the good work dedicated to optimization.

Sometimes, when the contents of the buffer change outside the current viewport, the wrong indent guidelines are shown.

**To Reproduce**
1. Open any file (using `src/nvim/shada.c` in the video)
2. Scroll down to a section with indents
3. Make a change that creates new indents and scrolls the window
4. Scroll the window downward for a bit
5. Press `u` to undo your edits in step 3
6. Scroll back to the section that you were in during step 5, and a bit lower
7. Observe the wrong indent guides

**Expected behavior**
The correct indent guides.

**Screenshots**

https://github.com/user-attachments/assets/4cc5843a-7910-43c9-8030-6577d9347da0

**Additional context**
This is just an example, but the situation has occurred several times during daily use. I've patched a workaround in my local version, where any time a render isn't "lazy", it invalidates the cache for the whole buffer. I haven't noticed any performance impact by doing this, but I haven't measured anything. I'd imagine you'd want to do something more clever, though.

**Comment by shellRaining** [comment]
I also frequently encounter this issue, but sorry, I've recently started an internship and found some other things that interest me, so it might be a long time before this issue gets resolved.
You can temporarily use indent_blankline as a substitute, and I will contact you once the issue is fixed.

**Comment by jbarap** [comment]
No worries, I'll see if I can tinker with it when I have some free time and may submit a PR. Best of luck with your internship!

**Comment by shellRaining** [comment]
@jbarap commits on the dev branch may have fixed this issue, feel free to give it a try.
