### ISSUE TITLE
Default config doesn't match types

### ISSUE THREAD

**Issue by nihaals** [shellRaining/hlchunk.nvim#140]
**Describe the bug**
Setting `style` to `vim.api.nvim_get_hl(...)` doesn't match the expected types despite being used in the default config both [documented](https://github.com/shellRaining/hlchunk.nvim/blob/4ceee25374d580ee5c3a65d1c68cfc638cb8c4a7/docs/en/indent.md?plain=1#L11-L20) and in [the source](https://github.com/shellRaining/hlchunk.nvim/blob/4ceee25374d580ee5c3a65d1c68cfc638cb8c4a7/lua/hlchunk/mods/indent/indent_conf.lua#L18-L26).

**To Reproduce**
1. Use something like the config below
2. Notice "Cannot assign `vim.api.keyset.hl_info` to `string|vim.api.keyset.highlight`."

```lua
---@module "hlchunk"
---@type HlChunk.UserConf
return {
  indent = {
    enable = true,
    style = {
      vim.api.nvim_get_hl(0, { name = "Whitespace" }),
    },
  },
}
```

**Expected behavior**
Type checking passes.

**Comment by shellRaining** [comment]
But in reality, their content is pretty much the same... well, I'll update the type annotation
