### ISSUE TITLE
hlchunk would freeze on deleting some line with the new treesitter

### ISSUE THREAD

**Issue by szcharlesji** [shellRaining/hlchunk.nvim#150]
**Describe the bug**
The whole editor would freeze after delete some lines that would result in a different tree structure

**To Reproduce**
1. Open a tree-parsed file
2. Select some text over more than a tree (i.e. not from a single stem)
3. freeze

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by uroybd** [comment]
It also happens if I go to the insert mode. Using `i` or `c`.

**Comment by uroybd** [comment]
#152 fixed this issue too.

**Comment by szcharlesji** [comment]
fixed by https://github.com/shellRaining/hlchunk.nvim/pull/152
