### ISSUE TITLE
Didn't get the coloring for chunk

### ISSUE THREAD

**Issue by nyngwang** [shellRaining/hlchunk.nvim#17]
**Describe the bug**

No coloring of the chunk line after starting Neovim.

**To Reproduce**

```lua
use {
  'shellRaining/hlchunk.nvim',
  config = function ()
    require('hlchunk').setup {
      chunk = {
        enable = true,
        use_treesitter = true,
        chars = {
          horizontal_line = "─",
          vertical_line = "│",
          left_top = "╭",
          left_bottom = "╰",
          right_arrow = "─",
        },
        style = "#00ffff",
      },
      line_num = {
        enable = true,
        style = "#806d9c",
      },
      indent = { enable = false },
      blank = { enable = false },
    }
  end
}
```

**Expected behavior**
Set the coloring of the chunk line.

**Screenshots**
![image](https://user-images.githubusercontent.com/24765272/236004115-cebf87e2-dbd3-40bd-805e-112c231457a0.png)

**Additional context**

**Comment by nyngwang** [comment]
workaround: If I call manually call `EnableHLChunk` again, the coloring is back. I guess this is related to `autocmd`(?)

**Comment by nyngwang** [comment]
> sorry but I can't reproduce this situation

Could you try changing to any other colorscheme and see if some of those `style`s might be overridden by some default values?

> can you provide more information?

I'm using lazy.nvim, and I don't enable its lazy-loading for most of my plugins.

**Comment by nyngwang** [comment]
Might be helpful for debugging: my current workaround is to create an `autocmd` like this: (I have another autocmd to trigger `ColorScheme` on `VimEnter`)

If this could be the way, then you could conditionally(since some people prefer to do this themselves) define a named `autocmd` in your source.

```lua
vim.api.nvim_create_autocmd({ 'ColorScheme' }, {
  pattern = '*',
  callback = function ()
    pcall(vim.cmd, 'EnableHLChunk')
    pcall(vim.cmd, 'EnableHLLineNum')
  end
})
```

**Comment by shellRaining** [comment]
OK，I will try it tormorrow~

**Comment by shellRaining** [comment]
thanks for your help, this issue has been solved~

**Comment by nyngwang** [comment]
Confirmed! Thank you!
