### ISSUE TITLE
The `then` block of if statement seems to be skipped

### ISSUE THREAD

**Issue by nyngwang** [shellRaining/hlchunk.nvim#18]
**Describe the bug**

When my cursor is on the same line with `then` (or inside the `then` block) the chunk line didn't point to it.

**To Reproduce**

```lua
use {
  'shellRaining/hlchunk.nvim',
  config = function ()
    require('hlchunk').setup {
      chunk = {
        enable = true,
        use_treesitter = true,
        chars = {
          horizontal_line = "─",
          vertical_line = "│",
          left_top = "╭",
          left_bottom = "╰",
          right_arrow = "─",
        },
        style = "#00ffff",
      },
      line_num = {
        enable = true,
        style = "#806d9c",
      },
      indent = { enable = false },
      blank = { enable = false },
    }
  end
}
```

example code:

```lua
if T.builtin[vim.bo.filetype]
  or T.builtin[vim.bo.buftype]
  or T.common[vim.bo.filetype]
then vim.cmd('IndentBlanklineDisable')
else vim.cmd('IndentBlanklineEnable') end
```

**Expected behavior**
When I move my cursor at the `then` block, then the chunk line should end at `then`.

**Screenshots**

https://user-images.githubusercontent.com/24765272/236005696-99b6d4bb-e5fd-41ef-983e-ab292d6013f1.mov

**Additional context**

**Comment by shellRaining** [comment]
ok, thanks for your report, i will try to fix this bug this weekend~

**Comment by nyngwang** [comment]
No need to fix it with a deadline :) My intention is to help you improve your plugin by providing all _problems_ to me. Feel free to ping me when you need some feedback after updating something.

**Comment by shellRaining** [comment]
fixed~, thanks for @Xiao-M0 contribution

**Comment by nyngwang** [comment]
Your refactoring seems to break the solution. See #26.
