### ISSUE TITLE
Bending on typing in the chunk/block

### ISSUE THREAD

**Issue by nyngwang** [shellRaining/hlchunk.nvim#19]
**Describe the bug**

The chunk line is not static during typing.

**To Reproduce**

```lua
use {
  'shellRaining/hlchunk.nvim',
  config = function ()
    require('hlchunk').setup {
      chunk = {
        enable = true,
        use_treesitter = true,
        chars = {
          horizontal_line = "─",
          vertical_line = "│",
          left_top = "╭",
          left_bottom = "╰",
          right_arrow = "─",
        },
        style = "#00ffff",
      },
      line_num = {
        enable = true,
        style = "#806d9c",
      },
      indent = { enable = false },
      blank = { enable = false },
    }
  end
}
```

example code:

```lua
vim.api.nvim_create_autocmd({ 'ColorScheme' }, {
  -- group = curfile_augroup,
  pattern = '*',
  callback = function ()
    vim.aj
  end
})
```

**Expected behavior**

I would expect the chunk line to be static when I was typing.

**Screenshots**

https://user-images.githubusercontent.com/24765272/236008513-36a5d81c-195a-42f9-80bf-962d3778678b.mov

**Additional context**

**Comment by shellRaining** [comment]
thanks for your report. The reason for this issue is that when the `TextChanged` autocmd executed, a rendering will also be performed. I will fix before this weekend~

**Comment by shellRaining** [comment]
fixed in https://github.com/shellRaining/hlchunk.nvim/commit/e1134c545ffe496de6ba7e0a631fc4931b757345. However, there is a small flaw: when in insert mode, moving the cursor within a line will not render the chunk, because when `TextChangedI` is triggered, `CursorMovedI` will also be triggered. I don't have a good time-saving solution for now.
