### ISSUE TITLE
[bug] treesitter overlay render in go source file

### ISSUE THREAD

**Issue by Xiao-M0** [shellRaining/hlchunk.nvim#2]
![Snipaste_2023-03-01_22-08-52](https://user-images.githubusercontent.com/115467839/222167477-d73c005d-9512-4d04-a6f3-ffe5459b5a3b.png)

当我开起treesitter后

在go语言下使用var时(只输入var)，会影响下面的代码正常显示，当输入完整后，显示又是正常的

**Comment by shellRaining** [comment]
I just reproduced this issue, I think it's because the treesitter thought it needed an extra indent on the third line, causing the overlay to render, I'll fix this in a future commit

**Comment by shellRaining** [comment]
the new version fix this bug, enjoy it!😄
