### ISSUE TITLE
Sometimes the highlighting of the number line(s) disappeared

### ISSUE THREAD

**Issue by nyngwang** [shellRaining/hlchunk.nvim#20]
**Describe the bug**

It seems that sometimes there was no highlighting when I moved my cursor to some nested block(in my case, Lua table). I only tested this with Lua.

**To Reproduce**

```lua
use {
  'shellRaining/hlchunk.nvim',
  config = function ()
    require('hlchunk').setup {
      chunk = {
        enable = true,
        use_treesitter = true,
        chars = {
          horizontal_line = "─",
          vertical_line = "│",
          left_top = "╭",
          left_bottom = "╰",
          right_arrow = "─",
        },
        style = "#00ffff",
      },
      line_num = {
        enable = true,
        style = "#806d9c",
      },
      indent = { enable = false },
      blank = { enable = false },
    }
  end
}
```

example code: turned out to be the config itself.

**Expected behavior**

I would expect the highlighting of the current chunk to always exist.

**Screenshots**

https://user-images.githubusercontent.com/24765272/236010572-310d2b87-e9cd-4911-be42-712fd3bf67dc.mov

**Additional context**

**Comment by shellRaining** [comment]
sorry, I did't mentioned in README about when to render line num, it also has an option `use_treesitter`, when not set this option, it will render between the two nearest curly braces at current cursor. so you can see it not render in line `761`.

so you can add `use_treesitter = true` in line_num option to fix this.

I will close this issue, if you have more question or encounter bug I will reopen it.

**Comment by nyngwang** [comment]
Roger that. Thanks for the reasoning and the solution. I will try it now.
