### ISSUE TITLE
Error executing lua callback: .../share/nvim/lazy/hlchunk.nvim/lua/hlchunk/mods/chunk.lua:93: index out of range

### ISSUE THREAD

**Issue by nyngwang** [shellRaining/hlchunk.nvim#23]
**Describe the bug**

Got a kinda serious error when pressing `n` to jump to the next matching by `/`:

```
Error detected while processing CursorMoved Autocommands for "*.lua":
Error executing lua callback: .../share/nvim/lazy/hlchunk.nvim/lua/hlchunk/mods/chunk.lua:93: index out of range
stack traceback:
	[C]: in function 'str_byteindex'
	.../share/nvim/lazy/hlchunk.nvim/lua/hlchunk/mods/chunk.lua:93: in function 'render'
	.../share/nvim/lazy/hlchunk.nvim/lua/hlchunk/mods/chunk.lua:146: in function <.../share/nvim/lazy/hlchunk.nvim/lua/hlchunk/mods/chunk.lua:145>
```

**To Reproduce**

1. Start Neovim
2. Open two vsplits A|B.
3. Try to open a file on B, where you will have a long line such that the `chunk.chars.left_top` will be invisible after scrolling right, e.g. `z50l`.
4. You will get the same error after 3.

**Expected behavior**

No error, and the jump(the default behaviour of `n`) should succeed.

**Screenshots**

**Additional context**

**Comment by nyngwang** [comment]
handled by #24

**Comment by shellRaining** [comment]
very thanks for your contribution, I not consider nerd font at first 😄
