### ISSUE TITLE
[bug] hl_chunk wrong rendering the chunk

### ISSUE THREAD

**Issue by Xiao-M0** [shellRaining/hlchunk.nvim#3]
![Snipaste_2023-03-01_22-10-29](https://user-images.githubusercontent.com/115467839/222169485-be83016b-6100-47a6-8d2b-a8b30b5e9aaa.png)

当我光标在`for j `上时,它不是`for j` 这个代码块

函数也是这样

when one hunk is in another hunk, it will highlight the outer hunk, such as this situation under, when cursor at x, expect highlighting the inner hunk at right

```
{
    {

    },
 x  {

    }
}
```

**Comment by shellRaining** [comment]
the definition of chunk in this plugin is `the closest pair of curly braces and the code in between`, it may describe not precise, it is the closest *outer* braces, so cause this situation, this is really counter-intuitive so

**Comment by shellRaining** [comment]
you can set treesitter options to avoid this problem. the solution not to use treesitter I have not idea... if you can fix it, welcome PR
