### ISSUE TITLE
Feature Request: Ignore filetypes

### ISSUE THREAD

**Issue by juiceDeLemon** [shellRaining/hlchunk.nvim#33]
**Is your feature request related to a problem? Please describe.**
I use alpha dashboard. I have no way to disable it in the config except manually disabling all of them using autocommand.

**Describe the solution you'd like**
Add ignore_ft = {} into the configuration

**Describe alternatives you've considered**
above

**Additional context**
<img width="1129" alt="Screenshot 2023-05-21 at 10 06 35" src="https://github.com/shellRaining/hlchunk.nvim/assets/77475400/8940fa5e-8b60-4a1e-9f3f-fc00bc198705">

**Comment by shellRaining** [comment]
OK, I will fix it today and notify you afterwards.

**Comment by shellRaining** [comment]
In fact, almost all mods have `support_filetypes` and `exclude_filetypes` options (maybe I should update README), the default ignore filetype is

```lua
M.exclude_filetypes = {
    aerial = true,
    dashboard = true,
    help = true,
    lspinfo = true,
    lspsagafinder = true,
    packer = true,
    checkhealth = true,
    man = true,
    mason = true,
    NvimTree = true,
    ["neo-tree"] = true,
    plugin = true,
    lazy = true,
    TelescopePrompt = true,
    [""] = true, -- because TelescopePrompt will set a empty ft, so add this.
    alpha = true,
}
```

the file path is `hlchunk/lua/hlchunk/utils/filetype.lua`. If you encounter any other filetype compatibility issues during use, feel free to modify this file here and submit a pull request.

**Comment by juiceDeLemon** [comment]
thanks
