### ISSUE TITLE
folded

### ISSUE THREAD

**Issue by Xiao-M0** [shellRaining/hlchunk.nvim#34]
![屏幕截图 2023-05-21 183323](https://github.com/shellRaining/hlchunk.nvim/assets/115467839/e3dc1741-4ff2-4952-a72b-bea5b92cb261)
![屏幕截图 2023-05-21 183313](https://github.com/shellRaining/hlchunk.nvim/assets/115467839/4fa67767-f5d7-4485-a083-54da23bb546c)

**Comment by shellRaining** [comment]
What kind of performance are you expecting?
