### ISSUE TITLE
stucked when opening .cs

### ISSUE THREAD

**Issue by postcypunk** [shellRaining/hlchunk.nvim#36]
**Describe the bug**
the chunk will stop moving when edting .cs files,disableHL the enableHL will refresh once,no error throwed ,but disableHL will pop a notice of my register
.lua and .py runs smoothly,

**To Reproduce**
open any .cs file

**Comment by shellRaining** [comment]
ok,  I will fix this today

**Comment by postcypunk** [comment]
#6 
ok  i found out why,

**Comment by shellRaining** [comment]
haha, if you found more bug about filetype, welcome to report and fix~
