### ISSUE TITLE
Chunk NOT working with *.jsx & *.tsx

### ISSUE THREAD

**Issue by npduykhoa** [shellRaining/hlchunk.nvim#41]
**Describe the bug**
I'm having issues with "chunk" in the filetypes: jsx and tsx. The chunks don't seem to work even though I've checked that the plugin supports both in support_filetypes.

 I have tested it with file formats .lua or .js, and the chunking works fine in those cases.

**Screenshots**
- Chunk working with .lua and .js:
![CleanShot 2023-05-29 at 12 35 43](https://github.com/shellRaining/hlchunk.nvim/assets/55375876/74ba7c2b-f479-4756-b7b4-75290ea120f7)
![CleanShot 2023-05-29 at 12 36 36](https://github.com/shellRaining/hlchunk.nvim/assets/55375876/f5c26862-1d04-4b20-add7-b918cbafadfc)

- Chunk NOT working with .jsx and .tsx:
![CleanShot 2023-05-29 at 12 37 49](https://github.com/shellRaining/hlchunk.nvim/assets/55375876/128e2fab-7e1a-4373-b957-62a3bebc7775)
![CleanShot 2023-05-29 at 12 38 25](https://github.com/shellRaining/hlchunk.nvim/assets/55375876/a4adb957-4c84-4d3a-917a-9d45ae32d646)

Thank you, and I look forward to receiving a prompt response from you.

**Comment by shellRaining** [comment]
Sorry, but I was unable to reproduce how this issue occurred.

![image](https://github.com/shellRaining/hlchunk.nvim/assets/111564053/06fb3893-0bb3-40d1-b092-5e8b2c3b7fbb)

and the treesitter parser for jsx is same as javascript, so I am not sure what cause this problem...

**Comment by shellRaining** [comment]
Could you record a video or GIF to demonstrate this bug? and can you provide the config file about how to config `chunk`

**Comment by npduykhoa** [comment]
Hi @shellRaining,
I have fixed this problem by remove (rm -rf) folder **plugged/** (where contain plugins installed) and then re-install all plugins.
So, I think the issue I encountered before was due to "hlchunk" conflicting with one or some plugins (may be nvim-treesitter old version), resulting in the chunks not functioning as expected in JSX and TSX files.
Now, chunk has been worked in JSX and TSX.

**Working in JSX
https://github.com/shellRaining/hlchunk.nvim/assets/55375876/99313790-a6b0-4851-a608-f3b22f147002

**Working in TSX
![CleanShot 2023-06-02 at 05 14 09](https://github.com/shellRaining/hlchunk.nvim/assets/55375876/4f9264bd-3932-4725-83f4-46a49546db8d)

Thank you for creating this wonderful plugin, @shellRaining .

**Comment by shellRaining** [comment]
Glad to know that you have solved the problem. If you encounter any new bugs, please feel free to let me know at any time.

**Comment by ic-768** [comment]
![image](https://github.com/user-attachments/assets/74d8b599-adce-4105-88b4-b5109a383b35)

Chunk is highlighting the sibling relationship here instead of the scope of the whole scope of the parent tag.
I've seen it does this a lot in `.tsx` files, is this normal?

**Comment by shellRaining** [comment]
@ic-768 seems not correct... can you provide this piece of code, I write a test code but not reproduce this bug, and can you share the config of hlchunk (include version)

**Comment by ic-768** [comment]
> @ic-768 seems not correct... can you provide this piece of code, I write a test code but not reproduce this bug, and can you share the config of hlchunk (include version)

here's a simpler example:

![image](https://github.com/user-attachments/assets/5bb95014-75ab-4c54-82f3-b3ab2883b9a6)


```
const Test = () => {
  return (
    <div>
      <span>test</span>
      <span>test</span>
    </div>
  );
};
```

hlchunk installation using lazy.nvim:

plugin.lua:
```
return  {
    "shellRaining/hlchunk.nvim",
    event = { "BufReadPre", "BufNewFile" },
    config = function()
      require("hlchunk").setup({
        chunk = {
          enable = true,
          chars = {
            horizontal_line = "─",
            vertical_line = "│",
            left_top = "╭",
            left_bottom = "╰",
            right_arrow = ">",
          },
          style = "#806d9c",
        },
      })
    end
  },

```

not sure how to get the version, but I just installed it today

**Comment by shellRaining** [comment]
oh I found why cause this, I was using the JSX file type earlier, which prevented the bug from being reproduced. I will attempt to fix it~

**Comment by shellRaining** [comment]
The behavior of the TSX parser and the JSX parser is different.

tsx:
<img width="719" alt="image" src="https://github.com/user-attachments/assets/e4d7cf29-b8b6-4544-aa74-1b9711ea0ecd">

jsx:
<img width="738" alt="image" src="https://github.com/user-attachments/assets/487d3cac-fb09-4d36-a23a-6643e1c84a4a">

for the code you provide, tsx mark the `jsx_element` node start from 18-19, but jsx mark from 19-19. The former's judgment includes spaces and line breaks, but this behavior is quite strange, leading to your bug.

so it's hard to fix unless tsx parser become more precise...

**Comment by ic-768** [comment]
> The behavior of the TSX parser and the JSX parser is different.
> 
> tsx: <img alt="image" width="719" src="https://private-user-images.githubusercontent.com/111564053/348666394-e4d7cf29-b8b6-4544-aa74-1b9711ea0ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzk0OTksIm5iZiI6MTcyMTAzOTE5OSwicGF0aCI6Ii8xMTE1NjQwNTMvMzQ4NjY2Mzk0LWU0ZDdjZjI5LWI4YjYtNDU0NC1hYTc0LTFiOTcxMWVhMGVjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMDI2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGVjMDRmMWQ2MzQyZjY5OGM5ZDNiZjdhNTRhMDlhNjcxZDQ4MGRmM2Q2NDA2ZDhkMjRlNjNmYTdmMzAzNjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k0cegD3dJHLWqcIbPfXM0V0R6WH3JnNtm6PXzBbo7EQ">
> 
> jsx: <img alt="image" width="738" src="https://private-user-images.githubusercontent.com/111564053/348666519-487d3cac-fb09-4d36-a23a-6643e1c84a4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzk0OTksIm5iZiI6MTcyMTAzOTE5OSwicGF0aCI6Ii8xMTE1NjQwNTMvMzQ4NjY2NTE5LTQ4N2QzY2FjLWZiMDktNGQzNi1hMjNhLTY2NDNlMWM4NGE0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMDI2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWQ5ODE0N2Q0YThiNzVlZGY3YWViYTZmNjllMmMwMWE0ZTRmM2MwMTNiZGI5OTA4MWUxYzAwMDgyMmZiMDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M-1zCwy7jOBjI5RJyZVsISVb0szad-c98CvdZXcUGaU">
> 
> for the code you provide, tsx mark the `jsx_element` node start from 18-19, but jsx mark from 19-19. The former's judgment includes spaces and line breaks, but this behavior is quite strange, leading to your bug.
> 
> so it's hard to fix unless tsx parser become more precise...

Ahh that makes sense..  Thanks for all your work anyway :)

**Comment by lazydeveloper** [comment]
thanks for the beautiful plugin, coming from indent-blankline.nvim
for me chunk not working for me for .java file - reinstalling hlchunk didn't work

any one else have problem with .java files? any fixes or work arounds?

**Comment by shellRaining** [comment]
@lazydeveloper maybe you should reinstall java treesitter parser, It works for me


https://github.com/user-attachments/assets/62a42cdf-9b81-4a3f-93fd-c36d060b83e3

**Comment by lazydeveloper** [comment]
@shellRaining Installing [Treesitter](https://github.com/nvim-treesitter/nvim-treesitter) fixed my problem. Cheers!

Here my config - might come handy if someone else having the same issue. 

`    {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate',
    config = function()
      require'nvim-treesitter.configs'.setup {
        ensure_installed = {
          "java", "python", "javascript", "html", "css"
        },
        sync_install = false,
        auto_install = true,
        highlight = {
          enable = true,
          additional_vim_regex_highlighting = false,
        },
      }
    end
  },`

**Comment by dhruvindsd-dev** [comment]
> The behavior of the TSX parser and the JSX parser is different.
> 
> tsx: <img alt="image" width="719" src="https://private-user-images.githubusercontent.com/111564053/348666394-e4d7cf29-b8b6-4544-aa74-1b9711ea0ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjYwOTYsIm5iZiI6MTcyNDE2NTc5NiwicGF0aCI6Ii8xMTE1NjQwNTMvMzQ4NjY2Mzk0LWU0ZDdjZjI5LWI4YjYtNDU0NC1hYTc0LTFiOTcxMWVhMGVjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxNDU2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjA1YWY1NWNlOWExMzBhMzkzNzFlZTdjNTBlYmJhMDk3ZDZmODg3ODNjYWQ5MmYzYWEwYjkwYTk2NGUzZWI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TXAbOeAbUEhn0ENyQ2R-RyBO_MZs7vJM6HhuF5gRuik">
> 
> jsx: <img alt="image" width="738" src="https://private-user-images.githubusercontent.com/111564053/348666519-487d3cac-fb09-4d36-a23a-6643e1c84a4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNjYwOTYsIm5iZiI6MTcyNDE2NTc5NiwicGF0aCI6Ii8xMTE1NjQwNTMvMzQ4NjY2NTE5LTQ4N2QzY2FjLWZiMDktNGQzNi1hMjNhLTY2NDNlMWM4NGE0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMFQxNDU2MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGU1YmY0Mjk0Y2UzYWNhY2U1NjVkMGI2OWUxMDYwZWQwYTlmMGIwYWZmNmRmMzNmMzE5MThiN2Q0MWFlMTAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i--ZMgQrRlyNPboSIeZn-vWQMmrGD9abe4F7HB8RMGo">
> 
> for the code you provide, tsx mark the `jsx_element` node start from 18-19, but jsx mark from 19-19. The former's judgment includes spaces and line breaks, but this behavior is quite strange, leading to your bug.
> 
> so it's hard to fix unless tsx parser become more precise...

@shellRaining, do you think anything can be done about this? 
It just updated all the plugins today (after around 8months) and suddenly this issue popped up.

Thanks for this awesome plugin!!!

**Comment by dhruvindsd-dev** [comment]
No worries @shellRaining , thanks for the update! 

For anyone else facing this issue, I've found the older version of `nvim-treesitter-textobjects` and `treesitter` work.

You can use these specific commits: 

```jsx
  {
    "nvim-treesitter/nvim-treesitter-textobjects",
    commit = "95933e762e28f9d38b572d65e7e4da9d2f4d90cb",
  },
  {
    "nvim-treesitter/nvim-treesitter",
    commit = "62b0bb4f24ad09f535efe44cc9d088f90dcd2498",
  },
```

**Comment by shellRaining** [comment]
now seems work properly, close temporarily
