### ISSUE TITLE
Rendering error on the first line in a file.

### ISSUE THREAD

**Issue by Aumnescio** [shellRaining/hlchunk.nvim#42]
**Describe the bug**
In the situation explained below, the indent-guide characters improperly render on the first line of a file.

**Screenshots of the bug**
Text in the buffer:

![image](https://github.com/shellRaining/hlchunk.nvim/assets/100923931/025c5a79-911a-42c0-a0f3-9d90a95c2fd9)

Wrongly rendering indent-guide characters:

![image](https://github.com/shellRaining/hlchunk.nvim/assets/100923931/96c55e8f-3c12-49d5-b181-f011fa40fd33)

![image](https://github.com/shellRaining/hlchunk.nvim/assets/100923931/e8ea0377-16a4-45f5-9dec-70fd50e3e4f0)

**My setup**
Using `lazy.nvim`:

```lua
{
    "shellRaining/hlchunk.nvim",
    enabled = true,
    lazy = true,
    version = false,
    event = "UIEnter",

    config = function()
        require("hlchunk").setup({
            indent = {
                enable = true,
                use_treesitter = false,
                chars = { "│" },
                style = {
                    { fg = vim.fn.synIDattr(vim.fn.synIDtrans(vim.fn.hlID("AumIndentGuide")), "fg", "gui") },
                },
            },

            blank = {
                enable = false,
            },
            chunk = {
                enable = false,
            },
            line_num = {
                enable = false,
            },
        })
    end,
},
```

**To Reproduce**
1. In the hlchunk setup, enable at least `indent`. I have disabled the other modules: `blank`, `chunk` and `line_num`.
2. Open a empty file, for example: `temp.txt`
3. Enter any text on the first line, for example `test`.
4. Indent the first line 1 or more times, then unident it back. (Indenting the text N amount of times and then entering a new line before the first non-whitespace character in the line also causes the bug.)
6. Error: The indent characters remain, and replace characters on the line.

![image](https://github.com/shellRaining/hlchunk.nvim/assets/100923931/9446eef6-0e11-496e-b260-977a23d99e23)

**Expected behavior**
The indent-guide characters should not be rendered in this broken manner on the first line of the file.

**Comment by shellRaining** [comment]
It should have been resolved (because I haven't encountered this issue again). If come across this problem again, please feel free to let me know~😊

**Comment by Aumnescio** [comment]
I encountered this error on the last line of a file too.

![image](https://github.com/shellRaining/hlchunk.nvim/assets/100923931/6ba3507c-987d-4ee6-ab77-91f250a17b78)

Opening new scopes near the end of the file seems to cause it.

For example, when I insert: `{<CR>{<CR>`, (with the `{` pair autocompleting) at the bottom of a file, the final line bugs out.

![image](https://github.com/shellRaining/hlchunk.nvim/assets/100923931/2bc96f16-b8b1-4292-97ca-1d2b956b3598)
