### ISSUE TITLE
Indent-guide rendering issue on long lines, when view jumps horizontally.

### ISSUE THREAD

**Issue by Aumnescio** [shellRaining/hlchunk.nvim#43]
**Describe the bug**
When the Neovim screen or view jumps horizontally, the indent-guides occasionally remain visible, even though they should not be visible.

**To Reproduce**
1. Ensure wrap is disabled. (`set nowrap`)
2. Be inside a indented scope with indent-guides and very long lines that are not completely visible on the screen.
3. Jump to the end of line, for example by pressing `$` in Normal Mode - Visual error might occur.
4. Jump to the start of line, for example by pressing `0`, and move one line up/down.
5. Repeat steps `3` and `4` until visual indent-guide error occurs.

NOTE: It does not happen every single time, but very often.

**Expected behavior**
The indent-guides should not be visible in this situation.

**Screenshots**
Example situation:

![image](https://github.com/shellRaining/hlchunk.nvim/assets/100923931/3da0bf82-a905-4b32-9723-95713d46ce49)

Rendering error when jumping to the end of line:

![image](https://github.com/shellRaining/hlchunk.nvim/assets/100923931/a3fe2caa-b84d-412d-9f61-673cae81feca)

**Video Clip**

https://github.com/shellRaining/hlchunk.nvim/assets/100923931/7c801c12-82ff-4f3c-bd4f-749e0199c30d

**Comment by shellRaining** [comment]
let me have a look~

**Comment by shellRaining** [comment]
fixed in [586d607](https://github.com/shellRaining/hlchunk.nvim/commit/586d60741ebefb516ee9efd66766d3e6d2c823dd)

The issue occurred due to a problem in the caching algorithm design. I will refactor it later on.

**Comment by Aumnescio** [comment]
Seems to be working well. Thanks for quick fixes.
