### ISSUE TITLE
Another indent-guide rendering issue.

### ISSUE THREAD

**Issue by Aumnescio** [shellRaining/hlchunk.nvim#44]
**Describe the bug**
Indent-guides fail to draw or render if the screen is moved when the first columns in a line aren't visible.

**To Reproduce**
1. `:set nowrap`
2. Scroll the screen horizontally, for example by going to the end of a long line that doesn't fit on the screen.
3. Scroll the screen vertically, up or down.
4. Scroll the screen horizontally, back to the first column.
5. Scroll the screen vertically, back to where the screen was before step 3. (If you scrolled down, scroll back up.)
6. Error: Some indent-guides will not have been drawn in.

NOTE: At step 3, it is already possible that wrongly rendering indent-guides might be visible. (First screenshot below)

**Expected behavior**
No missing indent-guides. The drawing of the indent-guides should update correctly even when the columns aren't initially visible on the screen.

**Screenshots**

![image](https://github.com/shellRaining/hlchunk.nvim/assets/100923931/591bfb73-b932-4fec-ab19-ac528e60edc2)

![image](https://github.com/shellRaining/hlchunk.nvim/assets/100923931/92c8c913-150c-4143-a4af-8c91480903ea)

**Comment by shellRaining** [comment]
May I ask if you can provide the code that caused this error? It would be very helpful for me to reproduce this bug.

And for performance reasons, I only render the lines that appear on the current screen (with a certain degree of caching), so some extreme cases are unavoidable (I will point them out in the README later, but these extreme cases are almost impossible to occur when writing code and more likely to happen in Markdown files).

**Comment by shellRaining** [comment]
Of course, the issue you pointed out in the picture is indeed a bug~

**Comment by Aumnescio** [comment]
You mean the testfile used in the screenshots? As that was just a temporary file, I already removed it, but it is easily reproduceable in any file. I'll add another temp file here.

```rust
// File:        temp.rs

fn silly_thing(something_great: i32) -> String {
    // veeeeeeeeeeeeeeeeeerry long line of text oooooooooooooooooooo ooooooooooooooooooo oooooooooo oooooooooooooooo
    let thing = {
        // <- These indent guides
        // Will disappear
        // soon.
        // They refresh if typing characters
        // in Insert Mode.
        // line of whatever
        // line of whatever
        // line of whatever
    }
}













                                            // long thing oooooooooooooooooooooo ooooooooooooooooooooo
                                            // thing thing thing thing thing thing thing thing
                                            // thing thing thing thing thing thing thing thing
                                            // thing thing thing thing thing thing thing thing
                                            // thing thing thing thing thing thing thing thing
                                            // thing thing thing thing thing thing thing thing
                                            // thing thing thing thing thing thing thing thing
                                            // thing thing thing thing thing thing thing thing
                                            // thing thing thing thing thing thing thing thing




























// End of File
```

And a video of me causing the issues to occur:

https://github.com/shellRaining/hlchunk.nvim/assets/100923931/d1bd2352-9d2e-45fb-bb54-859bd2f32ade

This might be a bit confusing to look at, but should be helpful.

I move to the end of line, then scroll to the bottom of the file, and then reset the horizontal position. Once I scroll back up, the indent guides are missing.

You can see the indent-guides going kind of wild in general.

**Comment by shellRaining** [comment]
nice. I will fix this next weekend~

**Comment by shellRaining** [comment]
The reason for this issue is due to an error in the cache algorithm design, because not consider "nowrap" option. Perhaps I need more time to consider how to set up a correct cache algorithm.

**Comment by shellRaining** [comment]
After removing the cache  feature, this bug has not occurred again, although there is a slight decrease in performance now. The latest code has been pushed to the main branch. If you encounter any other problems,  feel free to raise an issue again~
