### ISSUE TITLE
Add option to disable vim.notify when EnableHL/DisableHL

### ISSUE THREAD

**Issue by davidosomething** [shellRaining/hlchunk.nvim#45]
**Describe the bug**

When using commands EnableHL and DisableHL with disabled mods, it vim.notify the mod status
Please provide option to turn off notifications

**To Reproduce**

- `:DisableHL` and `:EnableHL`, see notifications

**Expected behavior**

no notifications, just silently disable and re-enable

**Screenshots**

**Additional context**

**Comment by shellRaining** [comment]
I have added the `notify` option in the options of each mod. It has now been pushed to the dev branch. I'm not sure if it meets your requirements. Looking forward to your feedback.

**Comment by davidosomething** [comment]
it works for me!
