### ISSUE TITLE
Use callback for bg/fg color styles OR reconfigure mod

### ISSUE THREAD

**Issue by davidosomething** [shellRaining/hlchunk.nvim#46]
**Is your feature request related to a problem? Please describe.**

When assigning style bg/fg colors to any mod, the color is set forever

**Describe the solution you'd like**

Ability to use function as
```
local function get_indent_bg()
              if vim.g.color_name = "colorsa" then
 return vim.fn.synIDattr(
                vim.fn.synIDtrans(vim.fn.hlID("Whitespace")),
                "bg",
                "gui"
              )
else
 return vim.fn.synIDattr(
                vim.fn.synIDtrans(vim.fn.hlID("NonText")),
                "fg",
                "gui"
              )
end

style = {
  { bg = get_indent_bg, fg = get_indent_fg },
  { bg = get_indent_bg_alt, fg = get_indent_fg_alt },
}
```

OR

```
blank = require('hlchunk').get_mod('blank')
current = blank:get_options()
next = vim.tbl_extend('force', current, { style = new styles })
blank:set_options(next)

OR

blank:set_hl(OVERRIDES) -- set_hl from BaseMod with new param to set override
```

**Describe alternatives you've considered**

**Additional context**

**Comment by shellRaining** [comment]
Do you want the mod's bg/fg to change when vim.g.color_name is changed while nvim is running? (I guess)

**Comment by davidosomething** [comment]
yep!

**Comment by shellRaining** [comment]
I feel that this is a great idea, but could you provide more detailed usage scenarios? For example, how did you modify the vim.g.color_name variable at runtime? Did you achieve it by modifying the colorscheme?

**Comment by davidosomething** [comment]
it is automatically set whenever you change :colorscheme

try these commands:
```
:colo habamax
:=vim.g.colors_name
:colo elflord
:=vim.g.colors_name
```

Currently on autocmd ColorScheme (`:h ColorScheme`) I am re-running:

```
  require("hlchunk").setup({
    blank = {
      chars = { " " },
      enable = true,
      exclude_filetype = require("dko.utils.buffer").SPECIAL_FILETYPES,
      notify = false,
      style = {
        { bg = "", fg = "" },
        { bg = vim.g.colors_name == "meh" and "#242426" or "#f4f2ef" },
      },
    },
    chunk = {
      enable = true,
      exclude_filetypes = {
        sh = true
      },
      notify = false,
    },
    indent = { enable = false },
    line_num = { enable = false },
  })

```
and this works but has to reconfigure all plugins


see https://github.com/davidosomething/dotfiles/blob/dev/nvim/lua/dko/behaviors.lua#L80-L94
and https://github.com/davidosomething/dotfiles/blob/dev/nvim/lua/dko/colors.lua#L47-L85

**Comment by shellRaining** [comment]
the feature have been push to dev, looking forward to your reply~

**Comment by davidosomething** [comment]
yup, works for me!
