### ISSUE TITLE
exclude_filetypes check wrong

### ISSUE THREAD

**Issue by davidosomething** [shellRaining/hlchunk.nvim#47]
**Describe the bug**

mods currently check for

```lua
    if (not self.options.enable) or self.options.exclude_filetypes[vim.bo.filetype] then
```

so need to use this format for exclude_filetypes:

```lua
exclude_filetypes = {
  sh = true
}
```

not

```lua
exclude_filetypes = { "sh" }
```

as stated in https://github.com/shellRaining/hlchunk.nvim/blob/main/docs/en/indent.md

maybe change to

```lua
vim.tbl_contains(exclude_filetypes, vim.bo.filetype)
```

or update docs to use `{ ft1 = true, ft2 = true }`

**Comment by shellRaining** [comment]
Oh yes, I'm sorry. There were some error in the document.

**Comment by shellRaining** [comment]
This design is only for the convenience of coding, but it does feel weirs for users. If there are similar feedback in the future, I will make some changes accordingly.
