### ISSUE TITLE
silence "not have parser for FILETYPE" message

### ISSUE THREAD

**Issue by dotrakoun-clearstreet** [shellRaining/hlchunk.nvim#49]
**Is your feature request related to a problem? Please describe.**

When opening a file with no treesitter type, hlchunk complains "not have parser for FILETYPE"
(e.g. a `conf` file)

Want two options:

1. fallback to native indent instead of use treesitter
2. turn off the vim.notify_once warning https://github.com/shellRaining/hlchunk.nvim/blob/c5afaedf69b4e10e6f0774db2e7a2793acd06d64/lua/hlchunk/utils/utils.lua#L47

**Comment by shellRaining** [comment]
In fact, each plugin has a "notify" attribute that can be used to disable prompts. However, considering the importance of the information provided by treesitter prompts, I did not modify this part of the code. I will make changes to this part later.

**Comment by davidosomething** [comment]
thanks!
