### ISSUE TITLE
[bug] render chunk when cursor in a comment

### ISSUE THREAD

**Issue by Xiao-M0** [shellRaining/hlchunk.nvim#5]
![Snipaste_2023-03-15_08-37-03](https://user-images.githubusercontent.com/115467839/225173558-95465ebd-00c7-4b92-823a-02b452c1d867.png)
![Snipaste_2023-03-15_08-39-26](https://user-images.githubusercontent.com/115467839/225173672-0fe60a10-e177-4909-8120-1f413a479e4d.png)

它不可以忽略代码注释

**Comment by shellRaining** [comment]
<img width="513" alt="image" src="https://user-images.githubusercontent.com/111564053/233249865-80518cc2-1c71-4c35-9f40-39f244754c65.png">

thanks to [miversen33](https://github.com/shellRaining/hlchunk.nvim/commits?author=miversen33) contribution, you can use treesitter to avoid this problem, but it will not only hl the `{}` chunk... I will try to use treesitter to fix it completely next week~

**Comment by shellRaining** [comment]
I fixed this bug, but unfortunately not completely because multi-line comments require context judgment which can cause runtime lag. For now, I will close this issue and if there are new solutions in the future, I will fix it again.
