### ISSUE TITLE
Characters are hidden behind indent lines

### ISSUE THREAD

**Issue by serhez** [shellRaining/hlchunk.nvim#52]
Characters are sometimes hidden behind the indent lines (i.e., those generated by `indent` mode, not `chunk` or others).

I attach two screenshots, the first one having the indent lines enabled and the second one without them. As can be observed in the first screenshot, the parenthesis closing the `if` statement is hidden. Also, some of the initial letters of each line within the `if` statement are hidden. I believe the ideal solution would be to either start the indent line after the `:` happens in an `if` statement (at least on Python), or to simply hide the indent line whenever needed.

![Screenshot 2023-07-06 at 16 29 16](https://github.com/shellRaining/hlchunk.nvim/assets/18057093/2b933d42-d3d0-4e10-bc54-996ccc5ae6a3)
![Screenshot 2023-07-06 at 16 29 39](https://github.com/shellRaining/hlchunk.nvim/assets/18057093/017ff49a-8c1d-45b1-ba32-25f5dc02c3e3)

Thanks!

**Comment by shellRaining** [comment]
The latest code has been pushed.  maybe this situation will not happen again...🤔

**Comment by serhez** [comment]
@shellRaining Thanks for the work, but it still happens, exactly as shown in the pictures :(

**Comment by shellRaining** [comment]
Not sure if it's convenient to provide the test text in the image above? 

and have you tested setting the "use_treesitter" option to true for indent mod?

**Comment by serhez** [comment]
Oh! I had `use_treesitter = true`; if I set it to `false`, it works well it seems 👍🏻. If set to false, is the plugin querying the LSP server?

**Comment by shellRaining** [comment]
https://github.com/shellRaining/hlchunk.nvim/tree/854297526e1484e31e97b9370129a2e815ef0639

The readme of this commit have mentioned the difference between whether use treesitter. As follow

```
you can choose a different indent render mode, one is base treesitter, another is base on the number of blank. the advantage of treeitter is that it is very accurate, but it may have low performance, and doesn't support some filetype, such as markdown, if you choose the latter mode, it will render faster (maybe), but will have some issues in particular situation, example below.
```
