### ISSUE TITLE
Chunk & Line_num failing to get correct treesitter node.

### ISSUE THREAD

**Issue by ripjackie** [shellRaining/hlchunk.nvim#73]
**Describe the bug**
Chunk and line_num fail to get the correct treesitter node, only the outermost scope is highlighted. with use_treesitter = false both work as intended. Indent seems unaffected by treesitter.

**To Reproduce**
enable use_treesitter on chunk or line_num

**Expected behavior**
chunk & line_num draw as expected in the spec

**Screenshots**
use_treesitter = true as in screenshot:
![image](https://github.com/shellRaining/hlchunk.nvim/assets/5079105/127f543b-80ed-4baa-96e9-b6b40ab8785a)
use_treesitter = false as in screenshot:
![image](https://github.com/shellRaining/hlchunk.nvim/assets/5079105/851f3e9f-4c09-4ae8-b311-2c6495e87efc)

**Additional context**
treesitter configuration:
![image](https://github.com/shellRaining/hlchunk.nvim/assets/5079105/0e1da639-4b47-435a-b566-7c030b08cc28)

**Comment by ripjackie** [comment]
***Further Info:***
neovim build:
NVIM v0.10.0-dev-594ff34
Build type: RelWithDebInfo
LuaJIT 2.1.1696795921

***nvim-treesitter checkhealth:***

==============================================================================
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)
- OK `node` found v18.13.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (Debian 12.2.0-14) 12.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "x86_64",
  release = "5.15.90.1-microsoft-standard-WSL2",
  sysname = "Linux",
  version = "#1 SMP Fri Jan 27 02:56:13 UTC 2023"
} ~

Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - http                ✓ . . . ✓
  - json                ✓ ✓ ✓ ✓ .
  - lua                 ✓ ✓ ✓ ✓ ✓
  - markdown            ✓ . ✓ ✓ ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - query               ✓ ✓ ✓ ✓ ✓
  - tsx                 ✓ ✓ ✓ ✓ ✓
  - vim                 ✓ ✓ ✓ . ✓
  - vimdoc              ✓ . . . ✓
  - xml                 ✓ . ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang} ~

**Comment by shellRaining** [comment]
fixed in latest version
