### ISSUE TITLE
Indent lines are not shown in Python docstrings

### ISSUE THREAD

**Issue by serhez** [shellRaining/hlchunk.nvim#77]
**Describe the bug**
Indent lines are not shown in Python docstrings, as shown in the screenshot below.

**To Reproduce**
You can try the code in the screenshot. My config:

```lua
chunk = {
    enable = true,
    use_treesitter = true,
    notify = true,
    chars = {
        horizontal_line = icons.bar.horizontal_thin,
        vertical_line = icons.bar.vertical_center_thin,
        left_top = icons.bar.upper_left_corner_thin,
        left_bottom = icons.bar.lower_left_corner_thin,
        right_arrow = icons.bar.horizontal_thin,
    },
    style = {
        {
            fg = c.info_fg,
        },
    },
    exclude_filetypes = {
        qf = true,
        help = true,
        dapui_scopes = true,
        dapui_watches = true,
        dapui_stacks = true,
        dapui_breakpoints = true,
        dapui_console = true,
        ["dap-repl"] = true,
        harpoon = true,
        dropbar_menu = true,
        glow = true,
        aerial = true,
        dashboard = true,
        lspinfo = true,
        lspsagafinder = true,
        packer = true,
        checkhealth = true,
        man = true,
        mason = true,
        NvimTree = true,
        ["neo-tree"] = true,
        plugin = true,
        lazy = true,
        TelescopePrompt = true,
        [""] = true, -- because TelescopePrompt will set a empty ft, so add this.
        alpha = true,
        toggleterm = true,
        sagafinder = true,
        sagaoutline = true,
        better_term = true,
        fugitiveblame = true,
        Trouble = true,
        Outline = true,
        starter = true,
        NeogitPopup = true,
        NeogitStatus = true,
        DiffviewFiles = true,
        DiffviewFileHistory = true,
        DressingInput = true,
        spectre_panel = true,
        zsh = true,
        vuffers = true,
    },
},

indent = {
    enable = true,
    use_treesitter = true,
    chars = {
        icons.bar.vertical_center_thin,
    },
    style = {
        {
            fg = c.comment_fg,
        },
    },
},

line_num = {
    enable = false,
},

blank = {
    enable = false,
    chars = {
        " ",
    },
    style = {
        {
            bg = c.bg,
        },
        {
            bg = c.cursor_line_bg,
        },
    },
},
```

**Expected behavior**
I would expect the indent lines to be shown for the docstrings.

**Screenshots**
![Screenshot 2023-11-14 at 17 07 54](https://github.com/shellRaining/hlchunk.nvim/assets/18057093/194ffbdb-07c3-4700-9aa1-8aff11d0ad6d)

**Comment by shellRaining** [comment]
This problem is still related to the treesitter option. Treesitter seems to determine that the docstring indentation of Python is 0 by default. To solve it, a lot of special judgments must be added, so it will not be fixed in the near future.

**Comment by serhez** [comment]
It seems that the best option for now is to disable the treesitter option then, thanks!

**Comment by shellRaining** [comment]
In fact, except for this issue, I have fixed the previous two. If you can tolerate such a little bit of unsightliness, this option is still very nice~

**Comment by serhez** [comment]
> In fact, except for this issue, I have fixed the previous two. If you can tolerate such a little bit of unsightliness, this option is still very nice~
> 
> 
> 
> I will push the patch to main brach later

What would you say are the advantages of the treesitter option? I've been using the plugin today with `treesitter = false` and I haven't noticed anything much different, besides the indent lines not occluding real text.

**Comment by shellRaining** [comment]
if use `treesitter`, the last line show like this

<img width="426" alt="image" src="https://github.com/shellRaining/hlchunk.nvim/assets/111564053/085323bb-0f0f-440b-829d-fca3707107fa">

else

<img width="460" alt="image" src="https://github.com/shellRaining/hlchunk.nvim/assets/111564053/61f90f46-2042-44c4-890d-d7d79116e481">

Using `treesitter` can reduce such visual interference, but I have plans to improve the display of the latter in the future.

**Comment by serhez** [comment]
That makes sense, thanks for the example! ❤️

**Comment by bsoprojects** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!

**Comment by shellRaining** [comment]
fixed in dev branch, welcome to experience

**Comment by serhez** [comment]
Thanks!
