### ISSUE TITLE
Question- How do I disable the dots?

### ISSUE THREAD

**Issue by RhysFonville** [shellRaining/hlchunk.nvim#78]
**Describe the bug**
I'm unsure of how to disable the dots. They make everything look cluttered and messy.

**To Reproduce**
1. Go to .vimrc
2. Use the example for the indent mod that uses multiple chars
3. Exit and reopen vim

**Expected behavior**
The indentation should look like the example screenshot.

**Screenshots**
![image](https://github.com/shellRaining/hlchunk.nvim/assets/22686438/a7db81f1-8e65-4cf8-815a-00e9b1ba404e)

**Comment by shellRaining** [comment]
```lua
require("hlchunk").setup({
  blank = { enable = false }
})
```

you could just disable the mod, other mod is similar like this, you can find more options in README
