### ISSUE TITLE
Install with packer question

### ISSUE THREAD

**Issue by xuzixx** [shellRaining/hlchunk.nvim#82]
hlchunk commit id : a17b86f
nvim version: v0.8.3

Packer with this config installed seems no use.  

`use { "shellRaining/hlchunk.nvim" }`

and `:PackerStatus` can see `hlchunk.nvim` this plugin

When I try to use `EnableHL`  get err , `│E492: Not an editor command: EnableHL ` 

I change config like below get another error
```lua
     use {
      "shellRaining/hlchunk.nvim",
      config = function()
        require('hlchunk').setup({
            indent = {
                chars = { "│", "¦", "┆", "┊", },
                style = {
                    "#8B00FF",
                },
            },
            blank = {
                enable = false,
            }
        })
      end,
    }
```

```
packer.nvim: Error running config for hlchunk.nvim: ...ack/packer/start/hlchunk.nvim/lua/hlchunk/mods/blank.lua:25: attempt to call field 'nvim_get_hl' (a nil value)
```

**Comment by shellRaining** [comment]
OK, I will take a look

**Comment by shellRaining** [comment]
maybe neovim version is too low, nvim_get_hl is not supported yet...

**Comment by xuzixx** [comment]
> maybe neovim version is too low, nvim_get_hl is not supported yet...

那还是更新一下readm 里的nvim 版本吧

**Comment by xuzixx** [comment]
> maybe neovim version is too low, nvim_get_hl is not supported yet...

update to nvim 0.9.4 fix

**Comment by shellRaining** [comment]
thanks~
