### ISSUE TITLE
Indent lines get cleared on one window if scrolling the same buffer in another window

### ISSUE THREAD

**Issue by jbarap** [shellRaining/hlchunk.nvim#84]
**Describe the bug**
When viewing a single buffer in two windows simultaneously, the active window behaves as expected, but when scrolling the buffer on the active window, the indent lines on the secondary window get gradually cleared.

**To Reproduce**
1. Open any file, and go to a section with indent lines displayed (in the example neovim/src/nvim/eval/funcs.c)
2. Open a vertically split window (ctrl-w v)
3. Scroll the buffer down in one window
4. Watch as the indents disappear in the other window

**Expected behavior**
As long as a buffer is visible in a window from the active tab, the indent guides should stay visible in each window's viewport.

**Screenshots**
Both windows with indents:
![image](https://github.com/shellRaining/hlchunk.nvim/assets/57547764/6301d958-8eb7-4fe7-849b-e217e5c6eb4d)

As the right window is scrolled, the indents in the left window get cleared:
![image](https://github.com/shellRaining/hlchunk.nvim/assets/57547764/2345cc9f-a230-4f14-adb8-0eb6b6777197)

**Additional context**
Config:
```lua
      require("hlchunk").setup({
        indent = {
          chars = {
            "▏",
          },
        },
        blank = {
          enable = false,
        },
        chunk = {
          enable = false,
        },
        line_num = {
          enable = false,
        }
      })
```

Great job with the plugin!

**Comment by shellRaining** [comment]
thanks for detail report~

because render range only include current window, other part of same buffer will clear while rendering, this will be solved in next version

**Comment by jbarap** [comment]
Thank you, looking forward to the next version!

**Comment by shellRaining** [comment]
fixed in latest version
