### ISSUE TITLE
Laggy in diff-mode with a thousand lines folded

### ISSUE THREAD

**Issue by tknightz** [shellRaining/hlchunk.nvim#85]
**Describe the bug**
In diff-mode, Vim/Neovim uses different fold method, it can lead to thousands of unchanged lines will be folded. Rendering chunks in folded lines costs a lot of CPU resources and laggy while scrolling.

**To Reproduce**
1. You have a file > 3000 lines of code.
2. Make some changes near the end of file.
3. Open diffview
4. See the CPU percentage goes up and laggy while scrolling.

**Expected behavior**
Shouldn't render chunk in folded lines, or is there any way to disable it in diff-mode.

**Screenshots**
![image](https://github.com/shellRaining/hlchunk.nvim/assets/40225276/4556baa1-cbd5-4849-8ecb-c8719d43e3c6)

**Additional context**
Here is my `hlchunk` config:

```lua
{
    "shellRaining/hlchunk.nvim",
    config = function()
      require("hlchunk").setup({
        chunk = {
          notify = false,
          style = {
            { fg = "#c75ae8" },
            { fg = "#f65866" }, -- this fg is used to highlight wrong chunk
          },
        },
        blank = {
          enable = true,
          chars = { " " },
        },
        line_num = { enable = false },
      })
    end,
    event = "BufReadPre"
}
```

**Comment by shellRaining** [comment]
sorry for late reply, I found that whenever edit a big file (10w+ lines), it could be very laggy, and It not caused by my plugin, so... maybe I can't provide a solution if there are more info

or, maybe there is another way to prevent this, when the chunk is too big (like more than 500 lines), not render it, is this OK?

**Comment by Sotatek-TuyenHa** [comment]
> sorry for late reply, I found that whenever edit a big file (10w+ lines), it could be very laggy, and It not caused by my plugin, so... maybe I can't provide a solution if there are more info
> 
> or, maybe there is another way to prevent this, when the chunk is too big (like more than 500 lines), not render it, is this OK?

Yep. Is there any way to disable it in a big file, or I have to write autocmd for it?

**Comment by tknightz** [comment]
Yes! Is there any way to turn it off when editing a big file?

**Comment by PostCyberPunk** [comment]
> Yes! Is there any way to turn it off when editing a big file?

you can try #86 if you want to test,there is a new option choke_at_linecount,hint:you have to set for every mod
