### ISSUE TITLE
Render unaligned when `shiftwidth` is not matched with current buffer

### ISSUE THREAD

**Issue by konosubakonoakua** [shellRaining/hlchunk.nvim#88]
**Describe the bug**
If I have a file which use 4-space tab, but the vim set `shiftwidth=2`, the render is glitched.

**Expected behavior**
Shell we provide an option to let use choice which size of tab should be respected, the vim setting or file content.

**Comment by shellRaining** [comment]
It seems that what you want is the "guess indent" effect. I will try to implement it.

https://github.com/NMAC427/guess-indent.nvim

**Comment by shellRaining** [comment]
I found that `guess-indent` and `hlchunk` work well together, and `guess-indent` itself performs very well, so there is no need to add this part for now. If you are still interested in this issue, feel free to submit a pull request.

You can add an automatic command `bufReadPost` in base_mod, and set a callback function guess indent in this automatic command.
