### ISSUE TITLE
Can this effect be achieved? Similar to indent-rainbowline.nvim.

### ISSUE THREAD

**Issue by ian-ie** [shellRaining/hlchunk.nvim#91]
[indent-rainbowline.nvim](https://github.com/TheGLander/indent-rainbowline.nvim?tab=readme-ov-file)
![screenshot](https://github.com/shellRaining/hlchunk.nvim/assets/55068959/8c9cb644-cf1e-4fc9-adb8-33e12a4c7401)

**Comment by shellRaining** [comment]
yes, you can use blank mod to achieved this effect, by setting below:

```lua
hlchunk.setup({
    blank = {
        enable = true,
        chars = {
            " ",
        },
        style = {
            { bg = "#434437" },
            { bg = "#2f4440" },
            { bg = "#433054" },
            { bg = "#284251" },
        },
    },
})
```

these highlights are same with `indent-rainbowline.nvim`, I will provide a simpler setup method later.
