### ISSUE TITLE
Doesn't work in php

### ISSUE THREAD

**Issue by mostafaqanbaryan** [shellRaining/hlchunk.nvim#95]
**Describe the bug**
So I recently installed hlchunk and It's beautiful.

But something I came across is that it doesn't work well with php.

If you have a large file and move between lines, it's obvious that the chunk line is stuck on some other place. 

**To Reproduce**
Save the code as php and move between methods.

chunk should easily move between class and its methods

(If it's didn't happen, I would upload an screencast)
```
<?php

class test{
    function a(){
        echo 'test a';
    }

    function b(){
        echo 'test b';
    }
}
```

**Expected behavior**
As shown in screenshot, I've moved to `function b`, but chunk stuck on `function a`

**Screenshots**
![image](https://github.com/shellRaining/hlchunk.nvim/assets/94293456/d350e229-e24f-4315-a9d1-697126a4fa21)

**Additional context**
Tested with `lua` and `js`, but those work fine

**Comment by shellRaining** [comment]
sorry for late reply, I can't reproduce this bug, can you switch to dev branch and have a try again?

**Comment by mostafaqanbaryan** [comment]
> sorry for late reply, I can't reproduce this bug, can you switch to dev branch and have a try again?

I don't know if it was nvim 9 or hlchunk's previous commits, but it's now fixed on nvim 10.
Thank you!
